### ISSUE TITLE
Strava Lep odbrojavač :))

### ISSUE THREAD

**Issue by igorspasic** [HeapSpace/website#35]
Ovo bi bilo mega kul:)

http://hilios.github.io/jQuery.countdown/

Ali treba proveriti da li radi kao mobile verzija.

**Comment by dtasic** [comment]
koristio sam ranije jedan jos lepsi: http://flipclockjs.com/

trenutno ga stavljam

**Comment by igorspasic** [comment]
da!!!!

**Comment by dtasic** [comment]
ovo je ideja: https://picload.org/image/wcrlloi/big-countdown.jpg

pravim partial koji ce moci da bude:
- 'fixed' vrhu strane ili 'inline' bilo gde na strani
- sa event slikom ili bez
- sa backgroundom ili bez backgrounda

**Comment by igorspasic** [comment]
sliku eventa slobodno izbaci, po meni dosta samo da piše:

geeknight: 12 34 56 78

čisto da fokusiramo na brojke, a i da bi bio nešto uži po visini; meni super kul :)

**Comment by igorspasic** [comment]
+ da li može da broji do vremena početka eventa, a ne dana? - izgleda da treba da se ubaci neko delta vreme zbog razlika u vremenskoj zoni, mislim da se ovo hostuje u kaliforniji,
+ da li može da se smanji ceo partial na malim ekranima, ono bukvalno na 50% manje? (nije mnogo bitno)
