### ISSUE TITLE
Strana sa _svim_ događajima

### ISSUE THREAD

**Issue by igr** [HeapSpace/website#37]
Trenutno su izlistani samo neki poslednji događaji.
Za sada su to i svi, ali nam treba neka /events strana gde su svu.
ja ću ovo

**Comment by dtasic** [comment]
ona metoda sto sam napravio get_events() lista sve evente ako joj ne prosledis nijedan parametar.

**Comment by igorspasic** [comment]
kulkul,znam,  samo da primenimo na strani, sve ok
