### ISSUE TITLE
Integracija sa nekom online galerijom

### ISSUE THREAD

**Issue by igorspasic** [HeapSpace/website#38]
Da ne bi slike ručno prebacivali ovde, treba nam jedna galerija koja se ovde može uglaviti.

Recimo... flickr? ili možda baš meetup.com u iframe?

**Comment by dtasic** [comment]
Meetup ima REST API, mozemo tako

**Comment by igorspasic** [comment]
Ako ima API za slike, to može da bude najjednostavnije; pošto bi onda mogli da upload slike na meetup (sto i inace radimo), pa ih prikazemo nekako smisleno na strani... šta god, samo da bude praktično za sajt. 

Možda ima recimo flickr jquery gallery plugin, pa ćemo staviti galeriju na flickr i odatle vući, pošto slike ionako uploadujemo na više mesta
