### ISSUE TITLE
Da li smo mi beše imali neki FontAwesome ikonu za GeekNight?

### ISSUE THREAD

**Issue by igorspasic** [HeapSpace/website#45]
![2016-02-23_00-00-00](https://cloud.githubusercontent.com/assets/2280001/13235859/d35af910-d9c0-11e5-9656-a1155226ee80.jpeg)

:)))))))))

**Comment by dtasic** [comment]
imali smo, ali nema 'kind' atributa na geeknight index.md
sad sam dodao, i to kroz "Izmeni stranu" sa sajta :)
