### ISSUE TITLE
header links

### ISSUE THREAD

**Issue by igorspasic** [HeapSpace/website#7]
ddodaj 4 linka.

**Comment by igorspasic** [comment]
Ovde je problem dodati linkove kada se pređe u mobile mod - nema puno mesta gore za to.
Možda mogu ikoncice umesto toga?

**Comment by igorspasic** [comment]
Mogu i da budu samo slova 'D', 'B' i slično. Kao Adobe ikone.

**Comment by klomontes** [comment]
@igorspasic Zašto ne bi linkovi bili u okviru hamburger menija u mobile modu? Ljudi su navikli na taj pattern i može da stane krš linkova. :)

**Comment by igorspasic** [comment]
Tako je i bilo u originalnoj temi :)))
Probacu da vratim to.
ne secam se sto sam ga batalio, verovatno jer sam zurio

**Comment by igorspasic** [comment]
Upravo dodajem nazad @klomontes

**Comment by igorspasic** [comment]
mnogo volim kada tupim ;)

**Comment by klomontes** [comment]
@igorspasic Lookin' good! :+1:
