### ISSUE TITLE
RSVP dugme vraća "Invalid Authorization request" sa meetup-a

### ISSUE THREAD

**Issue by zilet** [HeapSpace/website#79]
Kada se klikne na RSVP na http://heapspace.rs/geeknight/ ili http://heapspace.rs/techdorucak/ Meetup.com vrati "Invalid Authorization request" grešku.

![invalidauthrequest_meetup](https://cloud.githubusercontent.com/assets/1163484/13854626/a6cef1e4-ec6c-11e5-9516-4a822c1b072d.png)

**Comment by dtasic** [comment]
sredjeno
