### ISSUE TITLE
odbrojavac u headeru

### ISSUE THREAD

**Issue by igorspasic** [HeapSpace/website#9]
do prvog sledeceg dogadjaja. crvena boja, samo dan a ne i sta.

**Comment by igorspasic** [comment]
Hey @dtasic super! Jel možemo samo još i ovo da uradimo:

+ da odbrojavač bude u na sredini i da piše nešto kao:

    <ime_događaja>: <odbrojavač>

Na pr:

    GeekNight #4 za 5d 11h...

I da recimo se aktivira tek na 7 dana pre događaja.

**Comment by dtasic** [comment]
moze, sad cu da napravim

**Comment by igorspasic** [comment]
E da, i kada počne event, tj. kada dodje do 0, da nestane :)

Opušteno, ovo nije nešto hitno

**Comment by dtasic** [comment]
sve je reseno.
centrirano, prikazuje se samo 7 dana pre eventa. nema ga ako je prazno ili nije jos vreme da se prikaze. vrednost moze da se menja preko atributa data-daysbefore. 
automatski broji prethodne evente ili po 'kind' ili po 'title' atributu

**Comment by igorspasic** [comment]
Strava! Pogledaj i #35 za sledeću verziju
